-- ----------------------------------------------------------------------------
-- v0.2.3 — connector schema crawl + LLM-generated description
--
-- Stores the latest schema snapshot Argus has crawled for each Postgres
-- connector, plus an optional natural-language description generated by an
-- LLM. Investigators can reference the description so the AI "understands"
-- the source without re-introspecting on every run.
--
-- Idempotent. Also inlined into init.sql for first boot.
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS connector_schemas (
  connector_id   TEXT PRIMARY KEY REFERENCES connectors(id) ON DELETE CASCADE,
  schema_json    JSONB NOT NULL,           -- { tables: [...], counts: {...} }
  description    TEXT,                     -- LLM narrative; null while crawling
  description_at TIMESTAMPTZ,              -- when the LLM finished
  description_credential_id TEXT REFERENCES llm_credentials(id) ON DELETE SET NULL,
  crawled_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  crawl_error    TEXT
);
